"""capacity on events

Revision ID: a2ca4ce9ee96
Revises: 9db618fdb97f
Create Date: 2025-09-04 14:00:07.855768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ca4ce9ee96'
down_revision: Union[str, None] = '9db618fdb97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'capacity')
    # ### end Alembic commands ###
